---

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: create log file location
  block:
    - file:
        path: "/var/log/nginx/{{ domain }}"
        state: directory
        mode: 0755
        owner: nginx
        group: nginx
    - file:
        path: "{{ item }}"
        owner: nginx
        group: nginx
        state: touch
      loop:
        - "/var/log/nginx/{{ domain }}/access.log"
        - "/var/log/nginx/{{ domain }}/error.log"

- name: copy default config
  copy:
    dest: /etc/nginx/nginx.conf
    src: nginx.conf

- name: copy jenkins template
  template:
    dest:  /etc/nginx/conf.d/default.conf
    src: default.conf.j2
  notify: Reload Nginx


- name: create dir for ssl certs
  file:
    path: "/etc/nginx/ssl/{{ domain }}"
    state: directory
    mode: 0755
    owner: nginx
    group: nginx

- name: generate ssl cert for jenkins
  openssl_certificate:
    path: "/etc/nginx/ssl/{{ domain }}/{{ domain }}.crt"
    privatekey_path: "/etc/nginx/ssl/{{ domain }}/{{ domain}}.pem"
    csr_path: "/etc/nginx/ssl/{{ domain }}/{{ domain}}.csr"
    provider: selfsigned
